for pred_len in 96 192 336 720; do
    python -u run.py \
        --task_name finetune \
        --is_training 1 \
        --root_path ./datasets/ETT-small/ \
        --data_path ETTh1.csv \
        --model_id ETTh1 \
        --model TimeDART \
        --data ETTh1 \
        --features M \
        --input_len 336 \
        --label_len 48 \
        --pred_len $pred_len \
        --e_layers 4 \
        --d_layers 2 \
        --enc_in 7 \
        --dec_in 7 \
        --c_out 7 \
        --n_heads 16 \
        --d_model 128 \
        --cond_dim 128 \
        --d_ff 256 \
        --patch_len 4 \
        --stride 4 \
        --block_num 4 \
        --overlap_ratio 0.3 \
        --dropout 0.2 \
        --head_dropout 0.1 \
        --batch_size 16 \
        --gpu 2 \
        --lr_decay 0.5 \
        --lradj step \
        --time_steps 1000 \
        --sample_steps 25 \
        --scheduler cosine \
        --patience 3 \
        --learning_rate 0.0002 \
        --pct_start 0.3
done