for pred_len in 96; do
    python -u run.py \
        --task_name forecast \
        --is_training 0 \
        --root_path ./datasets/ETT-small/ \
        --data_path ETTh2.csv \
        --model_id ETTh2 \
        --model TimeDART \
        --data ETTh2 \
        --features M \
        --input_len 336 \
        --label_len 48 \
        --pred_len $pred_len \
        --e_layers 2 \
        --d_layers 2 \
        --enc_in 7 \
        --dec_in 7 \
        --c_out 7 \
        --n_heads 8 \
        --d_model 64 \
        --cond_dim 64 \
        --d_ff 256 \
        --patch_len 2 \
        --stride 2 \
        --generate_len 96 \
        --overlap_ratio 0.1 \
        --dropout 0.1 \
        --head_dropout 0.1 \
        --batch_size 16 \
        --gpu 1 \
        --lr_decay 0.5 \
        --lradj decay \
        --time_steps 50 \
        --sample_steps 50 \
        --scheduler cosine \
        --patience 3 \
        --learning_rate 0.0008 \
        --pct_start 0.3
done